// DATATYPE CONSTANTS
#define INTEGER 1
#define FLOAT 2
#define DOUBLE 3
#define CHARACTER 4
#define BOOLEAN 5
#define STRING 6

// EXPRESSION CONSTANTS
#define ASSIGNMENT 1
#define DECLARATION 2

// STATEMENT CONSTANTS
#define EXPRESSION 1
#define IFSTATEMENT 2

// OPERAND CONSTANTS
#define IDENTIFIER 1
#define NUMERIC 2
#define BINARYEXP 3
#define UNARYEXP 4
#define TERNARYEXP 5